# Generated by Django 5.1.4 on 2026-08-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image_url',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_file',
            field=models.FileField(blank=True, null=True, upload_to='deliveries/'),
        ),
        migrations.AddField(
            model_name='order',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='order_attachments/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gigs/'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('waived', 'Waived')], default='applied', max_length=20),
        ),
    ]
