# Generated by Django 5.2.17 on 2026-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_freelancerverification_revisioncharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerverification',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='freelancerverification',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/'),
        ),
        migrations.AlterField(
            model_name='freelancerverification',
            name='document_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar card'), ('pan', 'PAN card'), ('passport', 'Passport'), ('driving_license', 'Driving licence')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerverification',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification_selfies/'),
        ),
    ]
