# Generated by Django 5.2.17 on 2026-08-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_user_aadhaar_number_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerverification',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_number',
        ),
    ]
