# Generated by Django 5.1.4 on 2026-08-14 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_title', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ai', 'AI Services'), ('design', 'Graphics & Design'), ('wordpress', 'Programming & Tech'), ('voice', 'Music & Audio'), ('video', 'Video & Animation'), ('social', 'Digital Marketing'), ('seo', 'SEO'), ('illustration', 'Illustration'), ('translation', 'Writing & Translation'), ('books', 'Book Covers'), ('writing', 'Data Entry')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover', models.URLField()),
                ('delivery_time', models.CharField(max_length=50)),
                ('revision_number', models.IntegerField(default=1)),
                ('features', models.TextField(blank=True, help_text='Comma separated features')),
                ('total_stars', models.IntegerField(default=0)),
                ('star_number', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GigImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gigs.gig')),
            ],
        ),
    ]
